version: '3.8'

services:
  # Database
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: esmp_db
      MYSQL_USER: esmp_user
      MYSQL_PASSWORD: esmp_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - esmp-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  # Cache & Queue
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - esmp-network

  # Object Storage (S3 Compatible)
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9005:9000"
      - "9006:9001"
    volumes:
      - minio_data:/data
    networks:
      - esmp-network

  # Identity Provider
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.0
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
    networks:
      - esmp-network
    depends_on:
      - mysql

  # Observability
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - esmp-network

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    networks:
      - esmp-network
    depends_on:
      - prometheus

volumes:
  mysql_data:
  redis_data:
  minio_data:


networks:
  esmp-network:
    driver: bridge
